Refactored Nix config into modules and hosts for better reuse between systems

diff --git a/dotfiles/scripts/bash/default/git-identity b/dotfiles/scripts/bash/default/git-identity
--- a/dotfiles/scripts/bash/default/git-identity
+++ b/dotfiles/scripts/bash/default/git-identity
@@ -3,9 +3,9 @@
 # get each set of usernames from the git config (which will be generated from our `default.nix` above)
 IDENTITIES=$(git config --name-only --get-regexp "user.*..name" | sed -e 's/^user.//' -e 's/.name$//')
 # filter them with fzf
-ID=$(echo "${IDENTITIES}" | fzf -e -1 +m -q "$1")
+ID=$(echo "${IDENTITIES}" | fzf -e -1 +m -q "$1") || exit 1
 if ! git config --get-regexp "user.${ID}.name" >/dev/null; then
-	echo "Please use a valid git identity
+	echo "Unable to find ${ID}. Please use a valid git identity
 Options:"
 	git config --name-only --get-regexp "user.*..name" | sed -e 's/^user.//' -e 's/.name$//' -e 's/^/\t/'
 	exit 1
